<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Figures/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Ingeniería y Ciencia de Datos</h1>
        <h3 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;"><h3>Laboratorio de Procesamiento de Datos</h3>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Repaso Python y Librerías</h3>
    </div>
</div>


## Introducción

Python es un lenguaje de software libre, no tipado, interpretado y orientado a objetos. Se presenta como principal elección entre los lenguajes utilizados para aplicaciones de inteligencia artificial, particularmente de machine learning, junto con R, Matlab y Octave (dependiendo la comunidad que lo use).

Posee un enorme ecosistema de librerías de machine learning. Esto sumado a su flexibilidad y su simpleza de uso hacen que sea uno de los lenguajes más populares para la computación científica.

Algunos IDEs: Jupyter (web), Pycharm, Rodeo.


---

##  El entorno: Markdown y LaTeX

Antes de programar conviene conocer las **celdas de texto**. En Jupyter hay dos tipos de celdas:

| Tipo de celda | Para qué sirve | Cómo se ejecuta |
|---------------|----------------|-----------------|
| **Código** (`python`) | Escribir y correr código | `Shift + Enter` |
| **Markdown** | Explicar, documentar, fórmulas | `Shift + Enter` (se renderiza) |

Las celdas Markdown usan **Markdown** para el formato y **LaTeX** para las fórmulas matemáticas.


In [3]:
a=1
b=2
print(a+b)

3


Info adicional:

* [Markdown](https://daringfireball.net/projects/markdown/) es un conversor de texto plano a HTML. En los notebooks funciona como suerte de versión "liviana" de LaTex. Se usa en sitios como Slack, github (para los README), reddit.
* [LaTex](http://www.latex-project.org/) es un sistema de tipografía de alta calidad, que permite armar documentos con una sintaxis predefinida. Su sintaxis es mucho más verborrágica comparado con las herramientas típicas de ofimática, pero es mucho más flexible. A LaTex en los notebooks se lo utiliza principalmente para fórmulas.

Info adicional sobre LaTex, para aquellos interesados:
* Para armar documentos completos en LaTex de forma sencilla una buena alternativa es [Overleaf](https://www.overleaf.com/) (editor LaTex Web colaborativo). Por su parte, la alternativa que recomendamos es descargarlo mediante TexLive (en Debian/Ubuntu/Mint lo descargan con *sudo apt-get install texlive-full* (pesa 4Gb)) y editar los documentos mediante [Atom](http://atom.io/) y sus paquetes *latex* y *language-latex*

Para sus explicaciones en texto, jupyter por defecto utiliza Markdown. Para utilizar LaTex en un notebook, debe encerrarse la sentencia en \\$ ecuación \\$ para ecuaciones en la misma línea o bien entre \\$\\$ ecuación \\$\\$ para ecuaciones en una nueva línea.

Ejemplo $$\lim_{h \to 0} \frac{f(a+h)-f(a)}{h}$$

$\dot{x} = ax$

$$\dot{x} = ax + ax^2 + \frac{x}{5}$$

# 1. Estructuras de datos en Python

Una **estructura de datos** es una forma de organizar y almacenar varios valores dentro de una sola variable. Python trae cuatro estructuras integradas que son la base de todo el análisis de datos:

```mermaid
flowchart TD
    ED["Estructuras de datos<br/>integradas en Python"]
    ED --> L["list · lista<br/>[ ]"]
    ED --> T["tuple · tupla<br/>( )"]
    ED --> D["dict · diccionario<br/>{ clave: valor }"]
    ED --> S["set · conjunto<br/>{ }"]
    L --> L1["Ordenada · Mutable<br/>Permite duplicados"]
    T --> T1["Ordenada · Inmutable<br/>Permite duplicados"]
    D --> D1["Pares clave-valor<br/>Claves unicas"]
    S --> S1["Sin orden · Mutable<br/>Sin duplicados"]
```

| Estructura | Sintaxis | ¿Ordenada? | ¿Mutable? | ¿Duplicados? | Ejemplo de uso |
|-----------|----------|:----------:|:---------:|:------------:|----------------|
| **Lista** (`list`) | `[ ]` | ✅ | ✅ | ✅ | Colección de valores que cambia |
| **Tupla** (`tuple`) | `( )` | ✅ | ❌ | ✅ | Datos fijos (coordenadas, RGB) |
| **Diccionario** (`dict`) | `{k: v}` | ✅* | ✅ | Claves no | Buscar por clave (nombre → dato) |
| **Conjunto** (`set`) | `{ }` | ❌ | ✅ | ❌ | Elementos únicos, operaciones de conjuntos |

<sub>*Desde Python 3.7 los diccionarios conservan el orden de inserción.</sub>

---

## 1.1 Listas (`list`)

La **lista** es la estructura más usada. Es una secuencia **ordenada** y **mutable** que puede contener elementos de cualquier tipo.

```mermaid
flowchart LR
    subgraph L["lista = [10, 20, 30, 40]"]
      direction LR
      i0["10<br/>indice 0"] --- i1["20<br/>indice 1"] --- i2["30<br/>indice 2"] --- i3["40<br/>indice 3"]
    end
```

>  **Indexación:** el primer elemento es el índice `0`. También puedes usar índices negativos: `-1` es el último elemento.

Veamos algo de código con una de las estructuras principales de Python...


In [4]:
# estructura fundamental de python: listas
lista = [1,2,3,4,6]
lista

[1, 2, 3, 4, 6]

In [5]:
print(lista)

[1, 2, 3, 4, 6]


In [6]:
type(lista)

list

In [7]:
a = 1
b = 1.5
c = 'Hola a todos'

In [8]:
type(a)

int

In [9]:
type(1)

int

In [10]:
type(b), type(c)

(float, str)

In [11]:
# principal característica: listas completamente flexibles
lista2 = [1,2] + [2,5]
lista2

[1, 2, 2, 5]

In [12]:
lista3 = [1,'aa', 0.5, True]
lista3

[1, 'aa', 0.5, True]

In [13]:
lista4 = ['a', 'b', 'c']
lista4

['a', 'b', 'c']

In [14]:
s1='abcd'
s2=' efg'
s1+s2

'abcd efg'

In [16]:
lista

[1, 2, 3, 4, 6]

In [15]:
# con len() podemos ver las dimensiones de la lista
len(lista)

5

In [17]:
lista[0] = 10

In [18]:
lista

[10, 2, 3, 4, 6]

#### Indexado y rebanado (*slicing*)

Para acceder a los elementos usamos corchetes `[ ]`. La sintaxis general del *slicing* es `lista[inicio:fin:paso]`, donde el elemento `fin` **no** se incluye.

```mermaid
flowchart LR
    subgraph P["['a', 'b', 'c', 'd', 'e']"]
      direction LR
      a["a<br/>0 / -5"] --- b["b<br/>1 / -4"] --- c["c<br/>2 / -3"] --- d["d<br/>3 / -2"] --- e["e<br/>4 / -1"]
    end
```

| Expresión | Resultado | Significado |
|-----------|-----------|-------------|
| `L[0]` | `'a'` | Primer elemento |
| `L[-1]` | `'e'` | Último elemento |
| `L[1:3]` | `['b','c']` | Del índice 1 al 3 (sin incluir 3) |
| `L[:2]` | `['a','b']` | Desde el inicio hasta 2 |
| `L[2:]` | `['c','d','e']` | Desde 2 hasta el final |
| `L[::2]` | `['a','c','e']` | Todos, de 2 en 2 |


In [19]:
# cuál es el elemento con índice 1 de la lista?
lista4[0]

'a'

In [20]:
lista4[0:2]

['a', 'b']

In [21]:
lista4[:2]

['a', 'b']

In [22]:
lista4

['a', 'b', 'c']

In [23]:
lista4[1:3]

['b', 'c']

In [24]:
# de manera similar...
lista4[1:]

['b', 'c']

In [25]:
lista4[:]

['a', 'b', 'c']

In [26]:
lista3

[1, 'aa', 0.5, True]

In [27]:
lista3[::2]

[1, 0.5]

In [28]:
lista3[::3]

[1, True]

#### Métodos más usados de las listas

Como las listas son **mutables**, tienen métodos para modificarlas *in place*:

| Método | Qué hace | Ejemplo |
|--------|----------|---------|
| `.append(x)` | Agrega `x` al final | `L.append(5)` |
| `.remove(x)` | Elimina la primera aparición de `x` | `L.remove('a')` |
| `.count(x)` | Cuenta cuántas veces aparece `x` | `L.count('a')` |
| `.reverse()` | Invierte el orden | `L.reverse()` |
| `.sort()` | Ordena la lista | `L.sort()` |
| `.pop(i)` | Quita y devuelve el elemento `i` | `L.pop()` |
| `len(L)` | Número de elementos (función) | `len(L)` |


In [29]:
lista3.append('5102')

In [30]:
lista3

[1, 'aa', 0.5, True, '5102']

In [31]:
lista3.append('5102')

In [32]:
lista3

[1, 'aa', 0.5, True, '5102', '5102']

In [33]:
lista3.count('5102')

2

In [34]:
lista3.remove('5102')

In [35]:
lista3

[1, 'aa', 0.5, True, '5102']

In [36]:
lista3.reverse()

In [37]:
lista3

['5102', True, 0.5, 'aa', 1]

In [38]:
lista

[10, 2, 3, 4, 6]

In [39]:
lista.sort()

In [40]:
lista

[2, 3, 4, 6, 10]

In [41]:
lista[::-1]

[10, 6, 4, 3, 2]

In [42]:
lista3.remove('5102')

In [43]:
lista3

[True, 0.5, 'aa', 1]

In [44]:
lista3.remove('5102')

ValueError: list.remove(x): x not in list

#### Listas anidadas (matrices)

Una lista puede contener otras listas. Así se representa una **matriz**: para acceder a un elemento se usan dos índices `mat[fila][columna]`.

```mermaid
flowchart TD
    M["mat"] --> F0["fila 0 → [1, 3, 5]"]
    M --> F1["fila 1 → [5, 8, 9]"]
    M --> F2["fila 2 → [1, 1, 1]"]
    F1 --> E["mat[1][1] = 8"]
```


In [45]:
# o también...
mat = [[1,3,5],
       [5,8,9],
       [1,1,1]]
mat

[[1, 3, 5], [5, 8, 9], [1, 1, 1]]

In [46]:
print(mat)

[[1, 3, 5], [5, 8, 9], [1, 1, 1]]


In [47]:
mat[1]

[5, 8, 9]

In [48]:
mat[1][1]

8

In [50]:
mat[0][1]

3

# 2. Estructuras de control

Las estructuras de control deciden **qué** código se ejecuta y **cuántas veces**. En Python los bloques se delimitan por **indentación** (sangría), no por llaves.

>  **Importante:** la indentación (normalmente 4 espacios) es obligatoria en Python. Define qué instrucciones pertenecen a cada bloque.

## 2.1 Condicional `if` / `elif` / `else`

Permite ejecutar un bloque **solo si** se cumple una condición.

```mermaid
flowchart TD
    A["Evaluar condicion"] -->|Verdadero| B["Ejecuta bloque if"]
    A -->|Falso| C{"Hay elif?"}
    C -->|Si y se cumple| D["Ejecuta bloque elif"]
    C -->|Ninguna se cumple| E["Ejecuta bloque else"]
```

Los **operadores de comparación** devuelven `True` o `False`:

| Operador | Significado | | Operador | Significado |
|:--------:|-------------|---|:--------:|-------------|
| `==` | Igual a | | `>=` | Mayor o igual |
| `!=` | Distinto de | | `<` | Menor que |
| `>` | Mayor que | | `<=` | Menor o igual |


In [51]:
x = 2
y = 5

In [52]:
x >= y # ==, <=, !=, >, <, 

False

In [53]:
x==y

False

In [54]:
x<y

True

In [55]:
z=-1
print(z>0)

if z>0 :
    print('z>0')
elif z==0:
    print('z es 0')
else:
    print('z<0')

False
z<0


In [63]:
x = 0
if x:
    print(f'El valor de x es: {x}')
else:
    print('No imprime')
    

No imprime


In [67]:
x=0
bool(x)

False

In [57]:
x = 5.1
if x:
    print(f'El valor de x es: {x}')
else:
    print('No imprime')

El valor de x es: 5.1


In [70]:
x = 0.0
bool(x)

False

In [75]:
x = ''
if x:
    print(f'El valor de x es: {x}')
else:
    print('No imprime')

No imprime


In [76]:
bool(x)

False

## 2.2 Ciclo `for`

El ciclo `for` **repite** un bloque de código recorriendo un **iterable** (una lista, un rango, un diccionario, etc.). En cada vuelta, la variable toma el valor del siguiente elemento.

```mermaid
flowchart TD
    A["Inicio del for"] --> B{"Quedan<br/>elementos?"}
    B -->|Si| C["Toma el siguiente elemento"]
    C --> D["Ejecuta el bloque"]
    D --> B
    B -->|No| E["Fin del ciclo"]
```

>  `range(n)` genera los números `0, 1, ..., n-1`. Es la forma más común de repetir algo `n` veces.


In [78]:
type(range(5))

range

In [84]:
l_3 = list(range(5))

In [80]:
list(range(1,5))

[1, 2, 3, 4]

In [86]:
l_3[::2]

[0, 2, 4]

In [87]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [83]:
# for opera normalmente sobre rangos, listas u otro tipo de iterables
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9


In [92]:
lista_new = list(range(1,100,5))
lista_new


[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

In [95]:
lista_new2 = []

for i in range(len(lista_new)):
    if lista_new[i]%2==0:
        print(lista_new[i])
        lista_new2.append(lista_new[i])

6
16
26
36
46
56
66
76
86
96


In [96]:
lista_new2

[6, 16, 26, 36, 46, 56, 66, 76, 86, 96]

In [97]:
lista5 = []
for i in range(10):
    print(i)
    if i<=5:
        lista5.append(i)
print(lista5)

0
1
2
3
4
5
6
7
8
9
[0, 1, 2, 3, 4, 5]


In [99]:
l5 = [i for i in range(10) if i<=5]
l5

[0, 1, 2, 3, 4, 5]

In [98]:
lista6 =[]
for i in lista3:
    print(i)
    lista6.append(i)
lista6

True
0.5
aa
1


[True, 0.5, 'aa', 1]

# 3. Más estructuras de datos

## 3.1 Diccionarios (`dict`)

Un **diccionario** guarda pares **clave → valor**. En vez de acceder por posición (como en las listas), accedemos por su **clave**. Las claves deben ser **únicas**.

```mermaid
flowchart LR
    subgraph D["escuela = { }"]
      direction TB
      k1["'Nombre'"] --> v1["'ITESO'"]
      k2["'Ubicacion'"] --> v2["'Av. mmad'"]
      k3["'Horarios'"] --> v3["'9am - 6pm'"]
    end
```

| Operación | Sintaxis | Devuelve |
|-----------|----------|----------|
| Acceder a un valor | `d['clave']` | El valor asociado |
| Ver todas las claves | `d.keys()` | Lista de claves |
| Ver todos los valores | `d.values()` | Lista de valores |
| Ver pares clave-valor | `d.items()` | Pares `(clave, valor)` |
| Agregar / actualizar | `d['nueva'] = 10` | — |

>  La expresión `{k: v for (k, v) in zip(claves, valores)}` es una **comprensión de diccionario**: construye un `dict` a partir de dos listas.


In [100]:
a = {'c1':1, 'c2':2, 'c3':3}
print(a)

{'c1': 1, 'c2': 2, 'c3': 3}


In [101]:
type(a)

dict

In [102]:
a['c1']

1

In [103]:
a['c2']

2

In [104]:
a.values()

dict_values([1, 2, 3])

In [105]:
for i in a.values():
    print(i)

1
2
3


In [106]:
a.keys()

dict_keys(['c1', 'c2', 'c3'])

In [107]:
for c in a.keys():
    print(c)

c1
c2
c3


In [108]:
dias = ['Lun','Mar', 'Mier', 'Jue', 'Vie', 'Sab', 'Dom']
tmp = [28.0, 28.3, 27.0, 27.5, 28.6, 29.0, 30.0]

In [109]:
tmp_semana = {dias:tmp for (dias,tmp) in zip(dias,tmp)}
tmp_semana

{'Lun': 28.0,
 'Mar': 28.3,
 'Mier': 27.0,
 'Jue': 27.5,
 'Vie': 28.6,
 'Sab': 29.0,
 'Dom': 30.0}

In [110]:
tmp_semana['Lun']

28.0

In [111]:
tmp_semana.items()

dict_items([('Lun', 28.0), ('Mar', 28.3), ('Mier', 27.0), ('Jue', 27.5), ('Vie', 28.6), ('Sab', 29.0), ('Dom', 30.0)])

In [112]:
for keys,values in tmp_semana.items():
    print(keys)
    print(values)

Lun
28.0
Mar
28.3
Mier
27.0
Jue
27.5
Vie
28.6
Sab
29.0
Dom
30.0


In [113]:
a = {'c1':'#1234', 'c2':'#8594', 'c3':'#8723'}
a

{'c1': '#1234', 'c2': '#8594', 'c3': '#8723'}

In [114]:
escuela = {'Nombre':'ITESO', 'Ubicación': 'Av.mmad', 'Horarios': '9am - 6pm'}
escuela

{'Nombre': 'ITESO', 'Ubicación': 'Av.mmad', 'Horarios': '9am - 6pm'}

In [115]:
escuela['Ubicación']

'Av.mmad'

In [116]:
escuela.keys()

dict_keys(['Nombre', 'Ubicación', 'Horarios'])

In [117]:
escuela.values()

dict_values(['ITESO', 'Av.mmad', '9am - 6pm'])

In [118]:
Grupo = {'Nombre':['Alejandro', 'Ana', 'Ernesto'], 'Matricula': ['123','12341','8833'], 'Carrera':['Ing. Financiera','Ing. Financiera','Ing. Financiera']}
Grupo

{'Nombre': ['Alejandro', 'Ana', 'Ernesto'],
 'Matricula': ['123', '12341', '8833'],
 'Carrera': ['Ing. Financiera', 'Ing. Financiera', 'Ing. Financiera']}

In [119]:
Grupo.keys()

dict_keys(['Nombre', 'Matricula', 'Carrera'])

In [120]:
Grupo.values()

dict_values([['Alejandro', 'Ana', 'Ernesto'], ['123', '12341', '8833'], ['Ing. Financiera', 'Ing. Financiera', 'Ing. Financiera']])

In [121]:
for keys,values in Grupo.items():
    print(keys)
    print(Grupo[keys])

Nombre
['Alejandro', 'Ana', 'Ernesto']
Matricula
['123', '12341', '8833']
Carrera
['Ing. Financiera', 'Ing. Financiera', 'Ing. Financiera']


## 3.2 Tuplas (`tuple`)

Una **tupla** es como una lista, pero **inmutable**: una vez creada, **no se puede modificar** (no admite `append`, ni reasignar elementos). Se usa para datos que no deben cambiar.

```mermaid
flowchart LR
    subgraph LI["Lista [1, 2, 3]"]
      direction LR
      L1["Mutable ✅"] --- L2["lista[0] = 10 funciona"]
    end
    subgraph TU["Tupla (1, 2, 3)"]
      direction LR
      T1["Inmutable ❌"] --- T2["tupla[0] = 10 → TypeError"]
    end
```

>  Las tuplas se escriben con paréntesis `( )`, aunque los paréntesis son opcionales: `t = 1, 2, 3` también crea una tupla. Son útiles para **devolver varios valores** desde una función.


In [122]:
t1 = (1,2,3)
t1

(1, 2, 3)

In [123]:
type(t1)

tuple

In [124]:
t2 = 1,2,34,5
t2

(1, 2, 34, 5)

In [125]:
type(t2)

tuple

In [126]:
lista

[2, 3, 4, 6, 10]

In [127]:
lista[3] = 10

In [128]:
lista

[2, 3, 4, 10, 10]

In [129]:
t2 

(1, 2, 34, 5)

In [130]:
t2[2]

34

In [131]:
t2[2] = 10

TypeError: 'tuple' object does not support item assignment

In [132]:
t2

(1, 2, 34, 5)

In [133]:
for t in t2:
    print(t)

1
2
34
5


In [136]:
def mostrar(x,y,z):
    x = x*2
    y = y**2
    z = x+y+z
    
    return x,y,z,max(x,y,z)

In [137]:
mostrar(1,2,3)

(2, 4, 9, 9)

## 3.3 Conjuntos (`set`)

Un **conjunto** es una colección **desordenada** de elementos **únicos** (sin duplicados). Es ideal para eliminar repetidos y hacer operaciones de teoría de conjuntos (unión, intersección, diferencia).

```mermaid
flowchart LR
    A["Lista con duplicados<br/>[1, 2, 2, 3, 3, 3]"] -->|set| B["Conjunto<br/>{1, 2, 3}"]
```

| Operación | Símbolo | Método | Significado |
|-----------|:-------:|--------|-------------|
| Unión | `A | B` | `A.union(B)` | Elementos en A **o** B |
| Intersección | `A & B` | `A.intersection(B)` | Elementos en A **y** B |
| Diferencia | `A - B` | `A.difference(B)` | En A pero **no** en B |

>  Se crean con `{ }` o con `set(...)`. Un `{ }` vacío es un **diccionario**, no un conjunto: para un conjunto vacío usa `set()`.


In [138]:
# Un conjunto elimina automáticamente los duplicados
numeros = [1, 2, 2, 3, 3, 3, 4]
conjunto = set(numeros)
conjunto

{1, 2, 3, 4}

In [139]:
# Operaciones entre conjuntos
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print('Unión:', A | B)
print('Intersección:', A & B)
print('Diferencia A - B:', A - B)

Unión: {1, 2, 3, 4, 5, 6}
Intersección: {3, 4}
Diferencia A - B: {1, 2}


# 4. Librerías importantes

Una **librería** es un conjunto de código ya escrito que podemos reutilizar. Se importan con `import`. En ciencia de datos, tres son fundamentales:

```mermaid
flowchart LR
    NP["NumPy<br/>vectores y matrices"] --> PD["pandas<br/>datos tabulares"]
    NP --> MPL["Matplotlib<br/>graficas"]
    PD --> MPL
```

## 4.1 NumPy

Librería *open-source* que dota a Python de manejo de **vectores y matrices**, junto con un conjunto de funciones para procesarlas, asemejando a Python al manejo estilo Matlab.

El bloque básico de NumPy es el **`ndarray`**, un arreglo multidimensional de elementos **homogéneos** (todos del mismo tipo) y de tamaño fijo.

>  **Diferencia clave:** en una lista de Python `[1,2] + [3,4]` **concatena** → `[1,2,3,4]`. En un array de NumPy `np.array([1,2]) + np.array([3,4])` **suma** elemento a elemento → `[4,6]`.


In [140]:
# cuidado con la diferencia entre una lista "estándar" de python y un array de numpy!
l1 = [1,23.2,1]
l2 = [0,1,2]

In [141]:
l1+l2

[1, 23.2, 1, 0, 1, 2]

In [147]:
import numpy as np

In [148]:
a = np.array([1,2,3,4])

In [149]:
a

array([1, 2, 3, 4])

In [150]:
type(a)

numpy.ndarray

In [152]:
type(l1)

list

In [153]:
a.shape

(4,)

In [155]:
len(a)

4

In [156]:
a.dtype

dtype('int64')

In [157]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [158]:
a1 = np.array(['a','b','c'])
a1

array(['a', 'b', 'c'], dtype='<U1')

In [159]:
a2 = np.array((1.2,1.3,4.0))
a2

array([1.2, 1.3, 4. ])

In [160]:
a1 = np.array([1,2,3])
a2 = np.array([5,0,3*2])


In [161]:
a1.shape, a2.shape

((3,), (3,))

In [162]:
a1 + a2

array([6, 2, 9])

In [163]:
a1-a2

array([-4,  2, -3])

In [164]:
a1*2

array([2, 4, 6])

In [165]:
a1**2

array([1, 4, 9])

In [166]:
a1*a2

array([ 5,  0, 18])

In [167]:
# similarmente, no confundir la matriz que generamos con la lista de listas de python!!!
# son de dos tipos distintos
lm = [[1,2,3],
 [4,5,6],
 [7,8,9]] 
lm

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [168]:
type(lm)

list

In [169]:
M1 = np.array(lm)
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
M1 + 2*M1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [171]:
M1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [172]:
M1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [173]:
I = np.eye(5)

In [174]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [175]:
np.linalg.inv(I)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
# Principal ventaja de numpy: nos permite realizar fácil y eficientemente operaciones a nivel de lista
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
M1[1,1]

np.int64(5)

In [178]:
M1[:2,:2]

array([[1, 2],
       [4, 5]])

In [179]:
M1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [180]:
a

array([1, 2, 3, 4])

In [181]:
a1[:3]

array([1, 2, 3])

In [ ]:
# pedimos los elementos de índice 2 y 3 de la segunda columna
# (Notar que 2:4 equivale al intervalo [2,4), es decir que el elemento de índice 4 está excluído)


In [183]:
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
np.dot(M1,M1) # 3x3 3x3

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
matriz2 = np.array([[1,2],[3,4],[5,6]])
matriz2

In [ ]:
matriz2.shape

In [ ]:
M2 = matriz2.transpose()
M2

In [ ]:
M2.shape

In [ ]:
M1.shape

In [ ]:
np.dot(M2,M1)

In [ ]:
M1 @ M1

In [ ]:
np.dot(M1,M1)

In [ ]:
# otra operación comúnmente usada para construir o cambiar matrices:
# np.reshape
M3 = np.dot(M2,M1)
M3

In [ ]:
M3.shape

In [ ]:
M3.reshape(1,6)

In [ ]:
# comando muy útil para obtener ayuda sobre paquetes, métodos y demás
a4 = np.array([1,2,3,4,5])
a4


In [ ]:
a4 = np.arange(1,101)
a4

In [ ]:
a4.shape

In [ ]:
a4.reshape(2,50)

In [ ]:
help(np.arange)

In [ ]:
 np.arange(1,101,2)

In [ ]:
a5 = np.linspace(0,10,100)
a5

## 4.2 Matplotlib

Matplotlib es la librería estándar para la **visualización de datos**, algo fundamental en machine learning. Es muy flexible y simple de usar, y se integra con Jupyter para ver los gráficos dentro del notebook.

La función principal es `plot()`, que toma un número variable de argumentos y grafica de forma tan simple como escribiendo `plot(x, y)`.

```mermaid
flowchart LR
    A["Datos x, y"] --> B["plt.plot(x, y)"]
    B --> C["Titulo, ejes,<br/>leyenda, grid"]
    C --> D["plt.show()"]
```

| Función | Para qué sirve |
|---------|----------------|
| `plt.plot(x, y)` | Gráfica de línea |
| `plt.scatter(x, y)` | Diagrama de dispersión |
| `plt.title / xlabel / ylabel` | Títulos y etiquetas |
| `plt.legend()` | Muestra la leyenda |
| `plt.show()` | Dibuja la figura |


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(0,10,200)
x.shape

In [ ]:
x.min()

In [ ]:
x.max()

In [ ]:
y = np.sin(x)
y.shape

In [ ]:
plt.figure(figsize=(6,4))
plt.plot(x,y, 'y')
plt.title('Mi primera gráfica')
plt.xlabel('$x$')
plt.ylabel('$y=sin(x)$')
plt.grid()
plt.show()

In [ ]:
plt.figure(figsize=(6,4))
plt.plot(x,y, 'b',linewidth=2)
plt.title('Mi primera gráfica')
plt.xlabel('$x$')
plt.ylabel('$y=sin(x)$')
plt.xlim([0,4])
plt.ylim([0,1.5])
plt.grid()
plt.show()

In [ ]:
fig, ax = plt.subplots(figsize=(6,4))
ax.plot(x,y, 'y')
plt.xlim([0,12])
plt.ylim([0,2])

In [ ]:
help(plt.plot)

In [ ]:
plt.figure(figsize=(6,4))
plt.plot(x,np.sin(x),'^b', x, np.cos(x),'r')
plt.title('Mi primera gráfica')
plt.xlabel('$x$')
plt.ylabel('$y=sin(x)$')
#plt.xlim([0,4])
#plt.ylim([0,1.5])
plt.grid()
plt.show()

In [ ]:
plt.figure(figsize=(6,4))
plt.plot(x,np.sin(x),'b', label='$sin(x)$')
plt.plot(x, np.cos(x),'r',label='$cos(x)$')
plt.title('Mi primera gráfica')
plt.xlabel('$x$')
plt.ylabel('$y=sin(x)$')
plt.legend()
#plt.xlim([0,4])
#plt.ylim([0,1.5])
plt.grid()
plt.show()

In [ ]:
x2 = np.random.normal(size=500)
x2.shape

In [ ]:
y2 = np.random.normal(size=500)
y2.shape

In [ ]:
plt.figure(figsize=(8,6))
plt.scatter(x2,y2)
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.title('Ejemplo Scatter')

# 5. Definiendo funciones

Las funciones por defecto de Python son de mucha utilidad. Sin embargo, pronto nos daremos cuenta de que es aún más útil **definir nuestras propias funciones** para reutilizarlas cada vez que las necesitemos.

Una función recibe **entradas** (argumentos), ejecuta un bloque de código y opcionalmente **devuelve** un resultado con `return`.

```mermaid
flowchart LR
    A["Entradas<br/>argumentos"] --> B["def funcion(...):<br/>bloque de codigo"]
    B --> C["return<br/>resultado"]
```

>  **Anatomía:** `def nombre(args):` inicia la función; el código **indentado** es su cuerpo; `return` termina la función y entrega un valor. El texto entre `''' '''` al inicio es el *docstring* (documentación que muestra `help()`).

Por ejemplo, creemos una función que dados tres números, devuelva la mínima diferencia absoluta entre ellos.


In [ ]:
# Explicar acá la forma de definir una función
def diferencia_minima(a,b,c):
    '''
    Esta función regresa la diferencia mínima absoluta de tres números
    '''
    diff1 = abs(a-b)
    diff2 = abs(a-c)
    diff3 = abs(b-c)
    
    return min(diff1,diff2,diff3)
    

Las funciones comienzan con la palabra clave `def`, y el código indentado luego de los dos puntos `:` se corre cuando la función es llamada.

`return` es otra parablra clave que sólo se asocia con funciones. Cuando Python se encuentra un `return`, termina la función inmediatamente y devuelve el valor que hay seguido del `return`.

¿Qué hace específicamente la función que escribimos?

In [ ]:
# Ejemplo: llamar la función unas 3 veces
diferencia_minima(1,2,3)

In [ ]:
diferencia_minima(-1,2,3)

In [ ]:
diferencia_minima(-2.0,2.5,3.3)

In [ ]:
help(diferencia_minima)

Intentemos llamar `help` sobre la función

Bueno, Python tampoco es tan listo como para leer código y entregar una buena descripción de la función. Esto es trabajo del diseñador de la función: incluir la documentación.

¿Cómo se hace? (Recordar añadir un ejemplo)

In [ ]:
# Copiar y pegar la función, pero esta vez, incluir documentación de la misma
def diferencia_minima(a,b,c):
    '''
    Esta función regresa la diferencia mínima absoluta de tres números, recibe 3 argumentos a,b,c
    y devuelve la dif mínima.
    Ejemplo:
    diferencia_minima(-2.0,2.5,3.3)
    out: 0.7999999999999998
    '''
    diff1 = abs(a-b)
    diff2 = abs(a-c)
    diff3 = abs(b-c)
    
    return min(diff1,diff2,diff3)
    

In [ ]:
# Volver a llamar el help
help(diferencia_minima)

Muy bien. Ahora, podemos observar que podemos llamar esta función sobre diferentes números, incluso de diferentes tipos:

- Si todos son enteros, entonces nos retornará un entero.
- Si hay algún float, nos retornará un float.

In [ ]:
# Todos enteros
diferencia_minima(1,2,3)

In [ ]:
# Uno o más floats
diferencia_minima(-1.0,2.0,3.0)

In [ ]:
# String: TypeError
diferencia_minima('q','a','c')

####  Funciones que no devuelven

¿Qué pasa si no incluimos el `return` en nuestra función?

In [ ]:
# Ejemplo de función sin return
def imprimir(a):
    print(a)

In [ ]:
# Llamar la función un par de veces
imprimir('afnaksfna')

In [ ]:
a = imprimir('afnaksfna')
a

In [ ]:
a

In [ ]:
def imprimir2(a):
    print(a)
    return 'hola ' + str(a)

In [ ]:
a2 = imprimir2('Gaddiel')


In [ ]:
a2

####  Argumentos por defecto

Modificar la función `saludo` para que tenga un argumento por defecto.

In [ ]:
# Función saludo con argumento por defecto
def greetings(nombre):
    print(f'Bienvenido a la clase {nombre}')
    

In [ ]:
greetings('Gaddiel')

In [ ]:
def greetings(nombre = 'Alumno'):
    print(f'Bienvenido a la clase {nombre}')
    

In [ ]:
greetings('Alejandro')

# 6. La librería pandas 

</div>

**pandas** es la librería estándar de Python para el **análisis de datos tabulares** (datos organizados en filas y columnas, como una hoja de cálculo). Está construida sobre NumPy y es la herramienta central en ciencia de datos.

Trabaja con dos estructuras principales:

```mermaid
flowchart LR
    subgraph S["Series (1 dimension)"]
      direction TB
      s0["0 → 10"]
      s1["1 → 20"]
      s2["2 → 30"]
    end
    subgraph DF["DataFrame (2 dimensiones)"]
      direction TB
      h["nombre | edad | ciudad"]
      r1["Ana    |  23  | GDL"]
      r2["Luis   |  31  | CDMX"]
    end
    S -->|"varias Series<br/>forman un"| DF
```

| Estructura | Descripción | Analogía |
|-----------|-------------|----------|
| **`Series`** | Un arreglo unidimensional con etiquetas (índice) | Una **columna** |
| **`DataFrame`** | Una tabla bidimensional de filas y columnas | Una **hoja de cálculo** completa |

>  Convención universal: se importa como `import pandas as pd`. Si no está instalada: `pip install pandas`.


In [ ]:
import pandas as pd
import numpy as np

pd.__version__

## 6.1 Series

Una **`Series`** es una columna de datos con un **índice** (etiquetas) a la izquierda. Se puede crear a partir de una lista o de un diccionario.


In [ ]:
# Reutilizamos los datos de temperatura de la sección de diccionarios
dias = ['Lun', 'Mar', 'Mier', 'Jue', 'Vie', 'Sab', 'Dom']
tmp = [28.0, 28.3, 27.0, 27.5, 28.6, 29.0, 30.0]

temperaturas = pd.Series(tmp, index=dias, name='Temperatura')
temperaturas

In [ ]:
# Acceso por etiqueta y operaciones vectorizadas (como en NumPy)
print('Temperatura del miércoles:', temperaturas['Mier'])
print('Promedio de la semana:', temperaturas.mean())
print('Máxima:', temperaturas.max(), '| Mínima:', temperaturas.min())

## 6.2 DataFrame

El **`DataFrame`** es la estructura estrella de pandas: una **tabla** con filas y columnas etiquetadas. La forma más común de crearlo es a partir de un **diccionario**, donde cada clave es una columna.

```mermaid
flowchart TB
    subgraph DF["DataFrame"]
      direction TB
      COLS["Columnas → Nombre | Edad | Carrera"]
      IDX["Indice (filas) → 0, 1, 2"]
      DATA["Cada celda = un dato"]
    end
    COLS -.-> DATA
    IDX -.-> DATA
```

Retomemos el diccionario `Grupo` que vimos en la sección de diccionarios y convirtámoslo en un `DataFrame`.


In [ ]:
# Un DataFrame a partir de un diccionario: cada clave es una columna
Grupo = {
    'Nombre': ['Alejandro', 'Ana', 'Ernesto', 'Gaddiel'],
    'Edad': [20, 22, 21, 23],
    'Carrera': ['Ing. Financiera', 'Ing. Datos', 'Ing. Datos', 'Ing. Financiera'],
    'Promedio': [8.5, 9.2, 7.8, 9.6]
}

df = pd.DataFrame(Grupo)
df

### Explorar un DataFrame

Los primeros métodos que se usan al abrir un conjunto de datos:

| Método | Qué muestra |
|--------|-------------|
| `df.head(n)` | Las primeras `n` filas (5 por defecto) |
| `df.tail(n)` | Las últimas `n` filas |
| `df.shape` | `(filas, columnas)` |
| `df.columns` | Nombres de las columnas |
| `df.info()` | Tipos de datos y valores no nulos |
| `df.describe()` | Estadísticas de las columnas numéricas |


In [ ]:
# Dimensiones y nombres de columnas
print('Forma (filas, columnas):', df.shape)
print('Columnas:', list(df.columns))
df.head(2)

In [ ]:
# Estadísticas descriptivas de las columnas numéricas
df.describe()

## 6.3 Selección de datos: columnas, filas y filtros

```mermaid
flowchart TD
    A["DataFrame df"] --> B["Columna → df['Edad']"]
    A --> C["Por etiqueta → df.loc[fila, col]"]
    A --> D["Por posición → df.iloc[0, 1]"]
    A --> E["Filtro booleano → df[df['Edad'] > 21]"]
```

| Quiero... | Sintaxis |
|-----------|----------|
| Una columna | `df['Edad']` |
| Varias columnas | `df[['Nombre', 'Edad']]` |
| Una fila por **etiqueta** | `df.loc[0]` |
| Una celda por **posición** | `df.iloc[0, 1]` |
| Filas que cumplen una condición | `df[df['Edad'] > 21]` |


In [ ]:
# Seleccionar una columna (devuelve una Series)
df['Nombre']

In [ ]:
# Filtrado booleano: alumnos con promedio mayor o igual a 9.0
df[df['Promedio'] >= 9.0]

In [ ]:
# Crear una nueva columna a partir de otras
df['Aprobado'] = df['Promedio'] >= 8.0
df

## 6.4 Leer datos de un archivo CSV

Lo más habitual no es escribir los datos a mano, sino **cargarlos desde un archivo**. Con `pd.read_csv()` leemos un CSV directamente a un `DataFrame`.

```mermaid
flowchart LR
    A["archivo.csv<br/>en disco"] -->|"pd.read_csv()"| B["DataFrame"]
    B --> C["Explorar · limpiar<br/>analizar · graficar"]
```

Usaremos el archivo `housing_prices.csv` que está en esta misma carpeta y contiene el tamaño (`size`), número de recámaras (`n_bedrooms`) y precio (`price`) de varias casas.


In [ ]:
# Cargar el CSV (debe estar en la misma carpeta que este notebook)
casas = pd.read_csv('housing_prices.csv')
casas.head()

In [ ]:
# Un vistazo general: tipos de datos y estadísticas
casas.info()
casas.describe()

### Agrupar y resumir (`groupby`)

Una operación muy potente es **agrupar** filas que comparten un valor y calcular un resumen por grupo (promedio, conteo, suma...). Aquí agrupamos por número de recámaras.


In [ ]:
# Precio promedio y número de casas según la cantidad de recámaras
casas.groupby('n_bedrooms')['price'].agg(['mean', 'count'])

## 6.5 Visualizar con pandas + Matplotlib

pandas se integra con Matplotlib: casi cualquier `DataFrame` o `Series` tiene el método `.plot()`. Visualicemos la relación entre el **tamaño** de la casa y su **precio**.


In [ ]:
import matplotlib.pyplot as plt

casas.plot(x='size', y='price', kind='scatter', figsize=(7, 5),
           color='#e70488', title='Precio vs. tamaño de la casa')
plt.xlabel('Tamaño (pies²)')
plt.ylabel('Precio (USD)')
plt.grid(True)
plt.show()

# 7. Actividades

Pon en práctica lo aprendido. Resuelve cada ejercicio en las celdas de código de abajo.

### NumPy

**Ejercicio 1:**

1. Crear un vector con valores del 1 al 120.
2. Crear una función recibe_vector que reciba el vector y, dentro de la función, eleve al cuadrado aquellos números divisibles por 3, y regrese esos números en un nuevo vector.
3. Redimensionar el vector que devuelve la función anterior en una matriz de 20×2.
4. Crear una nueva matriz de 2×10 y multiplicarla por la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

**Ejercicio 2:**

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menorimc al que tiene mayor imc.

### Pandas

**Ejercicio 3:**

Usando el archivo `housing_prices.csv`:

1. Carga el archivo en un `DataFrame` con `pd.read_csv`.
2. Muestra las primeras 5 filas y las estadísticas descriptivas.
3. Crea una columna `precio_por_pie` = `price` / `size`.
4. Filtra y muestra solo las casas con más de 3 recámaras.
5. Calcula el precio promedio agrupando por número de recámaras (`groupby`).
6. Grafica un histograma de la columna `price` con `df['price'].plot(kind='hist')`.


In [ ]:
# Ejercicio 3: escribe aquí tu solución
